create table public.cart
(
    id          uuid                      not null
        constraint cart_pk
            primary key,
    dateCreated date default current_date not null
);



create table public.cartItem
(
    id         bigint generated by default as identity
        constraint cartItem_pk
            primary key,
    cart_id    uuid          not null
        constraint cartItem_cart_id_fk
            references public.cart (id)
            on delete cascade,
    product_id bigint        not null
        constraint cartItem_product_id_fk
            references public.product
            on delete cascade,
    quantity   int default 1 not null,
    constraint cartItem_product_cart_id_unique
        unique (product_id, cart_id)
);



