create table public.orders
(
    id bigint generated by default as identity constraint orders_pk  primary key,
    customer_id bigint not null constraint orders_user_id_fk references public.app_user,
    status varchar(20)  not null,
    created_at  date  not null,
    total_price  decimal(10, 2) not null
);



create table public.orderItems
(
    id  bigint generated by default as identity constraint orderItems_pk primary key,
    product_id  bigint  not null  constraint orderItems_product_id_fk references public.product(id),
    order_id  bigint   not null constraint orderItems_orders_id_fk    references public.orders (id),
    unit_price  decimal(10, 2) not null,
    quantity    integer        not null,
    total_price decimal(10, 2) not null
);



