spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store? CreateDataBaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
server:
  port: 8081