spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store? CreateDataBaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  jwt:
    secret: ${SECRET_KEY}
    accessTokenExpiration: 300
    refreshTokenExpiration: 604800

server:
  port: 8081


