spring:
  application:
    name: store
  datasource:
    url: jdbc:postgresql://localhost:5432/store? CreateDataBaseIfNotExist=true
    username: postgres
    password: postgres
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
  jwt:
    secretKey: ${SECRET_KEY}
    accessTokenExpiration: 54000
    refreshTokenExpiration: 604800

stripe:
  secretKey: ${STRIPE_SECRET_KEY}
  webhookSecretKey: ${STRIPE_WEBHOOK_SECRET_KEY}

websiteUrl: "http://localhost:4242"

server:
  port: 8081


