CREATE TABLE "user"
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name     VARCHAR(255),
    email    VARCHAR(255),
    password VARCHAR(255),
    CONSTRAINT pk_user PRIMARY KEY (id)
);

CREATE TABLE user_tag
(
    tag_id  INTEGER NOT NULL,
    user_id BIGINT  NOT NULL,
    CONSTRAINT pk_user_tag PRIMARY KEY (tag_id, user_id)
);

CREATE TABLE whishlist
(
    product_id BIGINT NOT NULL,
    user_id    BIGINT NOT NULL,
    CONSTRAINT pk_whishlist PRIMARY KEY (product_id, user_id)
);

ALTER TABLE "user"
    ADD CONSTRAINT uc_user_email UNIQUE (email);

ALTER TABLE user_tag
    ADD CONSTRAINT fk_user_tag_on_tag FOREIGN KEY (tag_id) REFERENCES tag (id);

ALTER TABLE user_tag
    ADD CONSTRAINT fk_user_tag_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);

ALTER TABLE whishlist
    ADD CONSTRAINT fk_whishlist_on_product FOREIGN KEY (product_id) REFERENCES product (id);

ALTER TABLE whishlist
    ADD CONSTRAINT fk_whishlist_on_user FOREIGN KEY (user_id) REFERENCES "user" (id);